### ISSUE TITLE
Original VBA Roster source available?

### ISSUE THREAD

**Issue by mountaincoder** [jaypalexa/roster#14]
Is the original VBA roster source available anymore? If so can I get a copy?

**Comment by jaypalexa** [comment]
Hello, @mountaincoder -- I have created a [repo for the VB.NET version of ROSTER](https://github.com/jaypalexa/roster-vb-net).  

Apologies for the dumpster fire that it is.  It has been about five years (and a different laptop!) since I have been in there...things got all tangled up.

Anyway, let me know if anything is missing or if you need any assistance, and I will try my best to help.

https://github.com/jaypalexa/roster-vb-net

**Comment by mountaincoder** [comment]
Thanks!
